### ISSUE TITLE
Monocular problem (site down)

### ISSUE THREAD

**Issue by carlosedubarreto** [davrempe/contact-human-dynamics#1]
Hello.
I was eager to test this solution, but right from the beggning I had problems with another repository.
I know its not your fault, but I think it would be nice to let you know, because anybody else will be able to build those other tools to test this solution, sadly.

Here is a issue I'm opened, just to other people, in case the have the same problem.

https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/issues/59

**Comment by davrempe** [comment]
Hello. Thanks for the heads up - I have contacted the author of Monocular Total Capture to see what can be done and I'll post any updates here.

**Comment by davrempe** [comment]
Update from the linked issue: "Hey guys, thank you for your interest, we are migrating the server to a new room, so link is temporarily down. We expect to restore the service early next week. Sorry for the inconvenience."

**Comment by carlosedubarreto** [comment]
Thanks a lot @davrempe .
So I'll have some time left to finish some other things before stay days in a row testing your solution 😁

**Comment by davrempe** [comment]
Looks like the server has been restored - closing this.

**Comment by carlosedubarreto** [comment]
Thanks a lot, now i can test it :)
