### ISSUE TITLE
apply foot contact on my own video

### ISSUE THREAD

**Issue by EEWenbinWu** [davrempe/contact-human-dynamics#11]
I got some video in the wild, however, there might be some problem with the rendering image. I can't get the result.
![image](https://user-images.githubusercontent.com/17973265/121292485-9de17d80-c91c-11eb-96f3-773c8b52ce72.png)
this cost more than one hour, and I still can't get the result.

**Comment by davrempe** [comment]
Hi. Yes, the visualization for contact detection uses matplotlib and is quite inefficient - it will take a long time and likely run out of memory if your video is longer than 2-3 seconds. I will try to update it when I get some time, but in the meantime I recommend running `run_detect_contacts.py` without the `--viz` flag and you should get the result in `foot_contacts.npy` quickly.

**Comment by visonpon** [comment]
Hi, @EEWenbinWu, you can decrease the frames till the render can process, on my machine , less than 250 frames can be rendered normal.

**Comment by EEWenbinWu** [comment]
thank you all, I'm trying to draw the results using opencv..
