### ISSUE TITLE
How to get the joint mapping between mixamo and smpl?

### ISSUE THREAD

**Issue by tszhang97** [davrempe/contact-human-dynamics#14]
https://github.com/davrempe/contact-human-dynamics/blob/ddde77df56de2afe2edfe8ef3a14f22ca7f1bbfc/src/utils/character_info_utils.py#L390 
How get these mappings? Thanks!

**Comment by davrempe** [comment]
These mapping were determined manually. To do this, you can use `BVH.load(bvh_file_name)` on the Mixamo character to get a list the joint names and their corresponding indices. Then you can open the Mixamo character in e.g. Blender to see where each of these joints are located on the skeleton and determine correspondences to the SMPL model this way.
