### ISSUE TITLE
Error building physics-based optimization part

### ISSUE THREAD

**Issue by vadeli** [davrempe/contact-human-dynamics#20]
Hello, Thanks for the great work. 
when I try to build the physics-based optimization I get the following error: 

```
contact-human-dynamics/towr_phys_optim/src/variables/nodes_variables_dynamic_phase_based.cpp:51:3: error: 

std::vector<towr::NodesVariablesPhaseBased::PolyInfo> towr::NodesVariablesPhaseBased::polynomial_info_’

is private within this context.
```
Could you please help me to solve this error?

**Comment by vadeli** [comment]
Problem solved.

**Comment by HitLyn** [comment]
How do you solve this problem? I have the same problem here

**Comment by HitLyn** [comment]
> How do you solve this problem? I have the same problem here

It's solved by using the updated version of tower.
