### ISSUE TITLE
Why is there a error: the openpose. bin file is missing?

### ISSUE THREAD

**Issue by 786739982** [davrempe/contact-human-dynamics#24]
Why is there a problem: the openpose. bin file is missing?
I am running your code[scripts/run_totalcap.py](https://github.com/davrempe/contact-human-dynamics/blob/main/scripts/run_totalcap.py) of “[contact-human-dynamics](https://github.com/davrempe/contact-human-dynamics)”，
but there was an error reported  “run_pipeline_no_ffmpeg.sh: line 37: ./build/examples/openpose/openpose.bin: No such file or directory”，
May I know how to solve this problem？

**Comment by davrempe** [comment]
Please follow the [instructions in the README](https://github.com/davrempe/contact-human-dynamics#monocular-total-capture-mtc) to install MTC, which involves installing OpenPose at this path. Then this issue should be resolved.
