### ISSUE TITLE
Files missing in “data” folder

### ISSUE THREAD

**Issue by zhaopy10** [davrempe/contact-human-dynamics#3]
Hello,
It seems that some python files in "data" folder are missing.

In "src/contact_learning/test.py", the following files are imported, but I can't find them in the repo.
import data.openpose_dataset as openpose_dataset
from data.openpose_dataset import OpenPoseDataset
from data.real_video_dataset import RealVideoDataset, TRAIN_DIM
from data.contact_data_utils import get_frame_paths

Could you please provide the missing files? Thanks

**Comment by davrempe** [comment]
Hello. I have added the missing files. Sorry about that there was a problem with the gitignore so they didn't get pushed.

**Comment by dengyang11** [comment]
I also meet same problem @davrempe

**Comment by davrempe** [comment]
@dengyang11 I pushed the files already a few days ago, you may need to pull the updates if you cloned the repo earlier than this.

**Comment by dengyang11** [comment]
Ok, thanks @davrempe
