### ISSUE TITLE
is there a way to obtain the joints position?

### ISSUE THREAD

**Issue by visonpon** [davrempe/contact-human-dynamics#8]
Hi @davrempe, thanks for your great work and I have got some good results based on your code.
 I also would like to know how to get and save joints especially the root position, hope you can give some advice, thanks~

**Comment by davrempe** [comment]
Yes, joints can be extracted from the output BVH files using `skeleton_fitting/ik/BVH` and `skeleton_fitting/ik/Animation`. Concretely, for the example data (dance1) which has final results in `dance1_ybot_durations.bvh`, you can use something like:

```
sys.path.extend(['skeleton_fitting/ik'])
import BVH
import Animation

anim, _, _ = BVH.load('path/to/dance1_ybot_durations.bvh')
joint_pos = Animation.positions_global(anim)
```

You can see a simliar example in the [visualization script](https://github.com/davrempe/contact-human-dynamics/blob/ddde77df56de2afe2edfe8ef3a14f22ca7f1bbfc/src/viz/viz_blender.py#L745) where I find the mean root position over time. To get information about joint ordering for the character you are using, see [this script](https://github.com/davrempe/contact-human-dynamics/blob/main/src/utils/character_info_utils.py).

**Comment by visonpon** [comment]
Hi@davrempe, thanks for your responce, I got another question that hope you can help.
In the `character_info_utils.py`,there are joints' index mapping between different models, I want to try the mapping between my own T pose and the combined model, but I don't know how to do it since the mapping seems like a manual design, can you give some more details about this?
